// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXPackageString = "1c245612-96af-490c-ac3e-7ed2faf53ac1";
        public static Guid guidVSIXPackage = new Guid(guidVSIXPackageString);

        public const string guidVSIXPackageCmdSetString = "9d169479-372d-4b21-a855-d4449ad5b742";
        public static Guid guidVSIXPackageCmdSet = new Guid(guidVSIXPackageCmdSetString);

        public const string guidImagesString = "7420ce07-09f0-4cc8-a79b-1d8d7e2eb1e3";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MyMenuItem = 0x1021;
        public const int MySubMenuGroup = 0x1022;
        public const int AnalyzeCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}