// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXPackageString = "73699f30-f957-4d5c-85f4-cac111489e4c";
        public static Guid guidVSIXPackage = new Guid(guidVSIXPackageString);

        public const string guidVSIXPackageCmdSetString = "0f1fc79c-87e1-4bc6-a703-e33c35705428";
        public static Guid guidVSIXPackageCmdSet = new Guid(guidVSIXPackageCmdSetString);

        public const string guidImagesString = "e1a62b98-d441-4cfd-a412-4b2c5b69235c";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}